# Generated by Django 4.1.5 on 2023-10-19 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_post_reading_time_alter_comment_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DR', 'draft'), ('PB', 'publish'), ('RJ', 'reject')], default='PB', max_length=3, verbose_name='وضعیت'),
        ),
        migrations.CreateModel(
            name='PostsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='موضوع')),
                ('discription', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ساخت')),
                ('imgfile', models.ImageField(upload_to='articles_img')),
                ('postFor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='app1.post', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'عکس پست',
                'verbose_name_plural': 'عکس پست ها',
            },
        ),
    ]
