# Generated by Django 4.1.5 on 2023-10-19 12:24

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_post_status_postsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsimage',
            name='imgfile',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=None, size=[300, 500], upload_to='articles_img/'),
        ),
        migrations.AlterField(
            model_name='postsimage',
            name='postFor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app1.post', verbose_name='عکس'),
        ),
    ]
