# Generated by Django 4.2.6 on 2023-10-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_account_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='Post',
            name='categories',
            field=models.CharField(choices=[('python', 'python'), ('go lang', 'go lang'), ('java', 'java'), ('other', 'other'), ('ai', 'ai ')], default='other', max_length=100),
        ),
    ]
