# Generated by Django 4.1.5 on 2023-10-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_post_reading_time_alter_post_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.CharField(choices=[('python', 'python'), ('go lang', 'go lang'), ('java', 'java'), ('other', 'other'), ('ai', 'ai ')], default='other', max_length=100),
        ),
    ]
